[package]
name = "smartimu"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
json = ["dep:serde-json-core"]
std-json = ["std", "dep:serde_json"]
std = []
esp = ["dep:esp-hal", "dep:embedded-hal"]

[dependencies]
async-trait.workspace = true
cobs.workspace = true
crc32fast.workspace = true
postcard.workspace = true
serde.workspace = true
serde-json-core = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror.workspace = true
embassy-time.workspace = true
hashbrown.workspace = true
libm.workspace = true
# ESP platform (optional)
embedded-hal = { workspace = true, optional = true }
esp-hal = { workspace = true, optional = true }
